version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
  livechat-backend:
    container_name: livechat-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
